---
- hosts: localhost
  sudo: yes
  tasks:
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: yes
  - name: Add multiple repositories into the same file (2/2)
    yum_repository:
      name: HandBrake
      description: Handbrake negativo17.org repo
      file: handbrake_repo
      baseurl: http://negativo17.org/repos/HandBrake/fedora-$releasever/$basearch/
      enabled: yes
      gpgkey: http://negativo17.org/repos/RPM-GPG-KEY-slaanesh
      gpgcheck: yes
  - name: Install HandBrake
    dnf: name=HandBrake-cli state=latest
  - name: Install Git 
    dnf: name=git state=latest
  - git: repo=https://github.com/nzrf/handbrake.git dest=/opt/handbrake
  - file: src=/opt/handbrake/handbrake-encode-all.sh dest=/usr/local/bin/handbrake-encode-all.sh mode=0755 owner=root group=root state=link
